from collections import OrderedDict
# import pprint

trustymail_results_1 = OrderedDict([('Domain', 'samhsa.gov'), ('Base Domain', 'samhsa.gov'), ('Live', True), ('MX Record', True), ('Mail Servers', 'smtp.ees.hhs.gov, smtp2.ees.hhs.gov'), ('Mail Server Ports Tested', '25, 587, 465'), ('Domain Supports SMTP Results', 'smtp.ees.hhs.gov:25, smtp2.ees.hhs.gov:25'), ('Domain Supports SMTP', True), ('Domain Supports STARTTLS Results', 'smtp.ees.hhs.gov:25, smtp2.ees.hhs.gov:25'), ('Domain Supports STARTTLS', True), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 a mx ip4:52.45.112.110 -all'), ('DMARC Record', True), ('Valid DMARC', True), ('DMARC Results', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', True), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov'), ('DMARC Forensic Report URIs', 'mailto:hhs@ruf.agari.com'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', None), ('Debug Info', '[STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out')])
# ^ BOD 18-01 compliant

trustymail_results_2 = OrderedDict([('Domain', 'clinicaltrial.gov'), ('Base Domain', 'clinicaltrial.gov'), ('Live', True), ('MX Record', False), ('Mail Servers', None), ('Mail Server Ports Tested', None), ('Domain Supports SMTP Results', None), ('Domain Supports SMTP', False), ('Domain Supports STARTTLS Results', None), ('Domain Supports STARTTLS', False), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 include:nih.gov ~all'), ('DMARC Record', True), ('Valid DMARC', True), ('DMARC Results', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', True), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:hhs@rua.agari.com'), ('DMARC Forensic Report URIs', 'mailto:hhs@ruf.agari.com'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', None), ('Debug Info', '[MX] In mx_scan at /var/task/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: clinicaltrial.gov. IN MX')])
# ^ Not BOD 18-01 compliant - 'Reports DMARC to CISA' - False
# ^ MX Record - False - "No SMTP servers" - So ignoring 'Uses STARTTLS'

trustymail_results_3 = OrderedDict([('Domain', 'hhsoig.gov'), ('Base Domain', 'hhsoig.gov'), ('Live', True), ('MX Record', True), ('Mail Servers', 'oig-hhs-gov.mail.protection.outlook.com'), ('Mail Server Ports Tested', '25, 587, 465'), ('Domain Supports SMTP Results', 'oig-hhs-gov.mail.protection.outlook.com:25'), ('Domain Supports SMTP', True), ('Domain Supports STARTTLS Results', 'oig-hhs-gov.mail.protection.outlook.com:25'), ('Domain Supports STARTTLS', True), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 a mx ptr -all'), ('DMARC Record', True), ('Valid DMARC', False), ('DMARC Results', 'v=DMARC1; p=reject; pct=100; rua=mailto:ISSO@oig.hhs.gov,mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:ISSO@oig.hhs.gov;'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', False), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; pct=100; rua=mailto:ISSO@oig.hhs.gov,mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:ISSO@oig.hhs.gov;'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:ISSO@oig.hhs.gov, mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov'), ('DMARC Forensic Report URIs', 'mailto:ISSO@oig.hhs.gov'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', '[DMARC] In handle_syntax_error at /var/task/trustymail/trustymail.py:669: Warning: The rua tag specifies 3 URIs.  Receivers are not required to send reports to more than two URIs - https://tools.ietf.org/html/rfc7489#section-6.2., [DMARC] In handle_syntax_error at /var/task/trustymail/trustymail.py:669: oig.hhs.gov does not indicate that it accepts DMARC reports about hhsoig.gov - https://tools.ietf.org/html/rfc7489#section-7.1, [DMARC] In handle_syntax_error at /var/task/trustymail/trustymail.py:669: oig.hhs.gov does not indicate that it accepts DMARC reports about hhsoig.gov - https://tools.ietf.org/html/rfc7489#section-7.1'), ('Debug Info', '[STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out')])
# ^ Not BOD 18-01 compliant for unknown reasons - CyHy says 'Has DMARC Policy of Reject' has a "Syntax Error" but above we see that 'DMARC Policy' is "reject" - CyHy says 'Reports DMARC to CISA' is "False" but above we see that the 'DMARC Aggregate Report URIs' includes "mailto:reports@dmarc.cyber.dhs.gov"

trustymail_results_4 = OrderedDict([('Domain', 'lrpmailings.od.nih.gov'), ('Base Domain', 'nih.gov'), ('Live', True), ('MX Record', True), ('Mail Servers', 'in.emailcc.com'), ('Mail Server Ports Tested', '25, 587, 465'), ('Domain Supports SMTP Results', 'in.emailcc.com:25'), ('Domain Supports SMTP', True), ('Domain Supports STARTTLS Results', None), ('Domain Supports STARTTLS', False), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 include:emailcc.com -all'), ('DMARC Record', True), ('Valid DMARC', True), ('DMARC Results', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', True), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov'), ('DMARC Forensic Report URIs', 'mailto:hhs@ruf.agari.com'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', None), ('Debug Info', '[STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out')])
# ^ Not BOD 18-01 compliant - 'Domain Supports STARTTLS' - False

trustymail_results_5 = OrderedDict([('Domain', 'selectagents.gov'), ('Base Domain', 'selectagents.gov'), ('Live', True), ('MX Record', True), ('Mail Servers', 'cluster5.us.messagelabs.com'), ('Mail Server Ports Tested', '25, 587, 465'), ('Domain Supports SMTP Results', 'cluster5.us.messagelabs.com:25'), ('Domain Supports SMTP', True), ('Domain Supports STARTTLS Results', 'cluster5.us.messagelabs.com:25'), ('Domain Supports STARTTLS', True), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 ip4:198.246.110.0/25 ip4:198.246.125.0/25 ip4:158.111.54.0/25 ip4:158.111.190.0/25 ip4:198.246.121.0/25 ip4:198.246.99.0 ip4:124.17.27.36 ip4:158.111.5.34 include:spf.messagelabs.com ~all'), ('DMARC Record', True), ('Valid DMARC', True), ('DMARC Results', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', True), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov'), ('DMARC Forensic Report URIs', 'mailto:hhs@ruf.agari.com'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', None), ('Debug Info', '[STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out, [STARTTLS] In starttls_scan at /var/task/trustymail/trustymail.py:118: timed out')])
# ^ Not BOD 18-01 compliant - "SMTP servers with weak crypto: cluster5.us.messagelabs.com:25 [SSLv3,3DES,RC4]"

trustymail_results_6 = OrderedDict([('Domain', 'medicaid.gov'), ('Base Domain', 'medicaid.gov'), ('Live', True), ('MX Record', False), ('Mail Servers', None), ('Mail Server Ports Tested', None), ('Domain Supports SMTP Results', None), ('Domain Supports SMTP', False), ('Domain Supports STARTTLS Results', None), ('Domain Supports STARTTLS', False), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 -all'), ('DMARC Record', True), ('Valid DMARC', True), ('DMARC Results', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', True), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:hhs@rua.agari.com,  mailto:reports@dmarc.cyber.dhs.gov'), ('DMARC Forensic Report URIs', 'mailto:hhs@ruf.agari.com'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', None), ('Debug Info', '[MX] In mx_scan at /var/task/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: medicaid.gov. IN MX')])
# ^ BOD 18-01 compliant despite "No SMTP servers"

trustymail_results_7 = OrderedDict([('Domain', 'eldercare.gov'), ('Base Domain', 'eldercare.gov'), ('Live', True), ('MX Record', False), ('Mail Servers', None), ('Mail Server Ports Tested', None), ('Domain Supports SMTP Results', None), ('Domain Supports SMTP', False), ('Domain Supports STARTTLS Results', None), ('Domain Supports STARTTLS', False), ('SPF Record', True), ('Valid SPF', True), ('SPF Results', 'v=spf1 -all'), ('DMARC Record', True), ('Valid DMARC', True), ('DMARC Results', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Record on Base Domain', True), ('Valid DMARC Record on Base Domain', True), ('DMARC Results on Base Domain', 'v=DMARC1; p=reject; fo=1; ri=3600; rua=mailto:hhs@rua.agari.com,mailto:reports@dmarc.cyber.dhs.gov; ruf=mailto:hhs@ruf.agari.com'), ('DMARC Policy', 'reject'), ('DMARC Policy Percentage', 100), ('DMARC Aggregate Report URIs', 'mailto:hhs@rua.agari.com, mailto:reports@dmarc.cyber.dhs.gov'), ('DMARC Forensic Report URIs', 'mailto:hhs@ruf.agari.com'), ('DMARC Has Aggregate Report URI', True), ('DMARC Has Forensic Report URI', True), ('Syntax Errors', None), ('Debug Info', '[MX] In mx_scan at /var/task/trustymail/trustymail.py:69: The DNS response does not contain an answer to the question: eldercare.gov. IN MX')])
# ^ BOD 18-01 compliant despite "No SMTP servers"

def trustymail_results_compliance_determination(data):
    # pp = pprint.PrettyPrinter(indent=4)
    # pp.pprint(trustymail_results)

    print('Domain Supports STARTTLS', data['Domain Supports STARTTLS'])
    print('Valid SPF', data['Valid SPF'])
    print('DMARC Policy', data['DMARC Policy'])
    print('DMARC Policy Percentage', data['DMARC Policy Percentage'])
    print('DMARC Aggregate Report URIs', data['DMARC Aggregate Report URIs'])

    no_smtp_servers = True if (not data['MX Record'] and data['Mail Servers'] == None and data['Mail Server Ports Tested'] == None and data['Domain Supports SMTP Results'] == None and not data['Domain Supports SMTP']) else False
    uses_starttls = True if data['Domain Supports STARTTLS'] else False
    spf_covered = True if (data['Valid SPF'] or data['DMARC Policy'] == "reject") else False
    dmarc_policy_reject = True if (data['DMARC Policy'] == "reject" and data['DMARC Policy Percentage'] == 100) else False
    reports_dmarc_cisa = True if ("cyber" in data['DMARC Aggregate Report URIs']) else False

    print('no_smtp_servers', no_smtp_servers)
    print('uses_starttls', uses_starttls)
    print('spf_covered', spf_covered)
    print('dmarc_policy_reject', dmarc_policy_reject)
    print('reports_dmarc_cisa', reports_dmarc_cisa)

    if ((uses_starttls or no_smtp_servers) and spf_covered and dmarc_policy_reject and reports_dmarc_cisa):
        print('compliant')
    else:
        print('non compliant')

trustymail_results_compliance_determination(trustymail_results_7)
